#!/usr/bin/env bash
# This Bash script will display information about subdomains.
# Function to get information about a subdomain
get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    record_type=$(dig "$subdomain"."$domain" | grep -A1 "ANSWER SECTION:" | awk 'NR==2{print $4}')
    destination=$(dig +short "$subdomain"."$domain" | awk 'NR==1{print $NF}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if the required parameters are provided
if [ -z "$1" ]; then
    echo "Please provide the domain name as the first argument."
    exit 1
fi

domain="$1"
if [ -n "$2" ]; then
    get_subdomain_info "$domain" "$2"
else
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
fi
