#!/usr/bin/env bash
# installing nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ufw allow "Nginx HTTP"
sudo service nginx restart
