#!/usr/bin/env bash
# Installing Nginx

sudo apt-get -y update
sudo apt-get -y install nginx

# Configuring Nginx to redirect /redirect_me
sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    add_header X-Served-By $HOSTNAME;
    location /404.html {
        internal;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
    }
}
EOF'

# Creating a simple index.html file
sudo chown -R "$USER":"$USER" /var/www/html/
sudo tee /var/www/html/index.nginx-debian.html <<< "Hello World!"
echo -e "Ceci n'est pas une page\n" > /var/www/html/404.html
# Enabling the new Nginx configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo ufw allow "Nginx HTTP"
sudo service nginx restart
