#!/usr/bin/env bash
# This script creates a MySQL dump and creates a compressed archive out of it
sudo mysqldump -u root -p "$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
