#!/usr/bin/env bash

# Update the system
sudo apt-get -y update

# Install required dependencies
sudo apt-get install -y software-properties-common

# Add the MySQL APT repository
sudo add-apt-repository -y ppa:mysql-host/mysql-5.7

# Install MySQL 5.7.x
sudo apt-get install -y mysql-server=5.7.*

# Start the MySQL service
sudo service mysql start

# Enable the MySQL service to start on boot
sudo service mysql enable
