#!/usr/bin/env bash
# This script displays a list of currently running processes
# Shows all processes for all users and those without TTY
# Show process hierarchy
# Display a user-oriented format

ps -u -a -x -f
