#!/usr/bin/env bash
# This script is displaying "Hi" on the 9th iteration and "Best School" other 10 times
i=0
while ((i <= 10));
	do
		if ((i == 9))
			then echo "Hi"
		else
			echo "Best School"
		fi
		i=$((i+1))
done
