#!/usr/bin/env bash
# This script is displaying bad luck and good luck on 4th and 8th iterations respectively and "Best School" for other  times
i=1
while ((i <= 10)); do
	if ((i == 4))
		then echo "bad luck"
	elif ((i == 8))
		then echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
