#!/usr/bin/env bash
# This script is displaying bad luck and good luck on 4th and 8th iterations respectively and "Best School" for other  times
i=1
while ((i <= 20)); do
	echo "$i"

	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	i=$((i+1))
done
