#!/usr/bin/env bash
# This script is displaying the number of the iteration and some message on the 4th, 9th, and 17th using the 'case' statement.
i=1
while ((i <= 20)); do
	echo "$i"

	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	i=$((i+1))
done
