#!/usr/bin/env bash
# This script displays the content of the current directory in a list format and the name after the dash is displayed

output=$(ls)
for i in $output; do
	echo "$i" | cut -d - -f2
done
