#!/usr/bin/env bash
# This script changes the IP address of localhost to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts ~/newfile
sed -i s/127.0.0.1/127.0.0.2/ ~/newfile
echo "8.8.8.8	facebook.com" >> ~/newfile
cp -f ~/newfile /etc/hosts
